name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machine

    env:
      # Define environment variables
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/{{ github.context.repo.repo }}:latest  # Use repo name for image name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME
